name: Pull Request Pipeline

on:
  pull_request:
    branches: [master]

env:
  NX_BASE: origin/master

jobs:
  validate:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure GitHub Package Registry
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
          npm config set @olddude:registry https://npm.pkg.github.com

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Security Audit
        run: npm audit || true

      - name: Install Dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Outdated Packages
        run: npm outdated || true

      - name: Lint Affected
        run: npm run affected:lint

      - name: Test Affected
        run: npm run affected:test

      - name: Build Affected
        run: npm run affected:build
